title: Navigation
  description: |
    Main navigation, will be different on every page depending on what case study the user is viewing.

patterns:
  navigation:
    fields:
      - name: data
        type: object
        data:
          source: "site.navigation[3]"
          type: Navigation
