title: Navigation
description: |
      Main navigation, will be different on every page depending on what case study the user is viewing.

patterns:
  nav:
    fields:
      - name: page
        type: object
        data:
          source: "site.pages[2]"
          type: Nav
