title: Navigation
  description: |
    Main navigation, will be different on every page depending on what case study the user is viewing.

patterns:
  nav:
    fields:
      - name: data
        type: object
        data:
          source: "site.navigation[0]"
          type: Nav
